import { PageFooter, type ReportMeta } from "./report-shell";

export function CoverPage({ meta }: { meta: ReportMeta }) {
  const periodFormatted = `${formatDate(meta.periodStart)} — ${formatDate(meta.periodEnd)}`;

  return (
    <div className="page" style={{ display: "flex", flexDirection: "column", justifyContent: "center" }}>
      {/* Logo area */}
      <div style={{ textAlign: "center", marginBottom: 48 }}>
        {meta.logoUrl ? (
          <img
            src={meta.logoUrl}
            alt={meta.organisationName}
            style={{ maxHeight: 80, maxWidth: 280, objectFit: "contain" }}
          />
        ) : (
          <div
            style={{
              display: "inline-block",
              padding: "12px 24px",
              background: "#0f172a",
              color: "#fff",
              fontSize: 24,
              fontWeight: 700,
              borderRadius: 8,
              letterSpacing: 1,
            }}
          >
            {meta.organisationName}
          </div>
        )}
      </div>

      {/* Title block */}
      <div style={{ textAlign: "center", marginBottom: 48 }}>
        <div
          style={{
            fontSize: 12,
            fontWeight: 600,
            color: "#3b82f6",
            textTransform: "uppercase",
            letterSpacing: 2,
            marginBottom: 16,
          }}
        >
          Progress Report
        </div>
        <h1 style={{ fontSize: 36, marginBottom: 8 }}>{meta.projectName}</h1>
        {meta.projectReference && (
          <div style={{ fontSize: 16, color: "#64748b", marginBottom: 4 }}>
            Ref: {meta.projectReference}
          </div>
        )}
      </div>

      {/* Details table */}
      <div
        style={{
          maxWidth: 400,
          margin: "0 auto",
          border: "1px solid #e2e8f0",
          borderRadius: 8,
          overflow: "hidden",
        }}
      >
        <table style={{ fontSize: 12 }}>
          <tbody>
            <DetailRow label="Contractor" value={meta.organisationName} />
            {meta.contractType && (
              <DetailRow label="Contract Type" value={formatContractType(meta.contractType)} />
            )}
            <DetailRow label="Report Number" value={`#${meta.reportNumber}`} />
            <DetailRow label="Reporting Period" value={periodFormatted} />
            <DetailRow label="Generated" value={formatDateTime(meta.generatedAt)} />
          </tbody>
        </table>
      </div>

      {/* Confidentiality notice */}
      <div
        style={{
          textAlign: "center",
          marginTop: 48,
          fontSize: 9,
          color: "#94a3b8",
          lineHeight: 1.6,
        }}
      >
        This document is confidential and intended solely for the named recipient(s).
        <br />
        Generated by SiteProof — Contractor Progress Evidence Tracker
      </div>

      <PageFooter meta={meta} pageNum={1} />
    </div>
  );
}

function DetailRow({ label, value }: { label: string; value: string }) {
  return (
    <tr>
      <td
        style={{
          fontWeight: 600,
          color: "#475569",
          width: "40%",
          padding: "10px 14px",
          background: "#f8fafc",
          borderBottom: "1px solid #e2e8f0",
        }}
      >
        {label}
      </td>
      <td
        style={{
          padding: "10px 14px",
          borderBottom: "1px solid #e2e8f0",
        }}
      >
        {value}
      </td>
    </tr>
  );
}

function formatDate(iso: string): string {
  return new Date(iso + "T00:00:00").toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function formatDateTime(iso: string): string {
  return new Date(iso).toLocaleString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatContractType(type: string): string {
  const map: Record<string, string> = {
    design_build: "Design & Build",
    traditional: "Traditional",
    management: "Management Contract",
    jct: "JCT",
    nec: "NEC",
    other: "Other",
  };
  return map[type] ?? type;
}
