import { PageFooter, type ReportMeta } from "./report-shell";

export interface SignatureData {
  role: "contractor" | "project_manager" | "client";
  name: string;
  title?: string;
  date?: string;
}

const ROLE_MAP: Record<string, string> = {
  contractor: "Contractor",
  project_manager: "Project Manager",
  client: "Client / Employer's Agent",
};

export function SignOffPage({
  meta,
  startPage,
  signatures = [],
}: {
  meta: ReportMeta;
  startPage: number;
  signatures?: SignatureData[];
}) {
  // Build a lookup of provided signatures by role
  const sigByRole = new Map(signatures.map((s) => [s.role, s]));
  return (
    <div className="page">
      <h2>Sign-Off</h2>
      <div className="text-sm text-muted" style={{ marginBottom: 24 }}>
        This report has been prepared using evidence submitted through SiteProof.
        All parties should review and sign below to confirm acceptance.
      </div>

      {/* Signature blocks */}
      <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>
        <SignatureBlock
          role="Contractor"
          description="I confirm that the progress described in this report is accurate and supported by the evidence provided."
          signature={sigByRole.get("contractor")}
        />
        <SignatureBlock
          role="Project Manager"
          description="I have reviewed the evidence and progress claimed in this report and confirm it is consistent with site observations."
          signature={sigByRole.get("project_manager")}
        />
        <SignatureBlock
          role="Client / Employer's Agent"
          description="I acknowledge receipt of this progress report and the evidence contained herein."
          signature={sigByRole.get("client")}
        />
      </div>

      {/* Legal disclaimer */}
      <div
        style={{
          marginTop: 40,
          padding: 16,
          background: "#f8fafc",
          borderRadius: 8,
          border: "1px solid #e2e8f0",
        }}
      >
        <h3 style={{ fontSize: 10, color: "#475569", marginBottom: 6 }}>
          Disclaimer
        </h3>
        <div style={{ fontSize: 8, color: "#64748b", lineHeight: 1.7 }}>
          <p style={{ marginBottom: 6 }}>
            This report has been automatically generated by SiteProof based on
            photographic and video evidence uploaded by site personnel. While every
            effort has been made to ensure accuracy, the report relies on the
            integrity of the submitted evidence including EXIF metadata, GPS
            coordinates, and timestamps embedded in the original media files.
          </p>
          <p style={{ marginBottom: 6 }}>
            SiteProof does not independently verify the physical progress on site.
            The GPS coordinates and timestamps are extracted from device metadata
            and have not been independently verified unless explicitly stated in the
            Verification section of this report.
          </p>
          <p style={{ marginBottom: 6 }}>
            This document is confidential and intended solely for the parties named
            above. Unauthorised distribution, copying, or disclosure of this report
            is prohibited. The document may be password-protected; recipients are
            responsible for maintaining the security of access credentials.
          </p>
          <p>
            Report generated on{" "}
            {new Date(meta.generatedAt).toLocaleString("en-GB", {
              day: "numeric",
              month: "long",
              year: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            })}{" "}
            by SiteProof v1.0.
          </p>
        </div>
      </div>

      <PageFooter meta={meta} pageNum={startPage} />
    </div>
  );
}

function SignatureBlock({
  role,
  description,
  signature,
}: {
  role: string;
  description: string;
  signature?: SignatureData;
}) {
  const isSigned = !!signature;

  return (
    <div
      style={{
        border: `1px solid ${isSigned ? "#86efac" : "#e2e8f0"}`,
        borderRadius: 8,
        padding: "16px 20px",
        background: isSigned ? "#f0fdf4" : "transparent",
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
        <div
          style={{
            fontSize: 13,
            fontWeight: 600,
            color: "#0f172a",
          }}
        >
          {role}
        </div>
        {isSigned && (
          <span
            className="badge badge-green"
            style={{ fontSize: 8 }}
          >
            Digitally Signed
          </span>
        )}
      </div>
      <div style={{ fontSize: 10, color: "#64748b", marginBottom: 16 }}>
        {description}
      </div>

      <div style={{ display: "flex", gap: 24 }}>
        <div style={{ flex: 2 }}>
          <div style={{ fontSize: 9, color: "#94a3b8", marginBottom: 4 }}>
            Name & Title
          </div>
          <div
            style={{
              borderBottom: `1px solid ${isSigned ? "#86efac" : "#cbd5e1"}`,
              height: 28,
              fontSize: 11,
              fontWeight: 500,
              color: "#0f172a",
              lineHeight: "28px",
            }}
          >
            {signature ? `${signature.name}${signature.title ? `, ${signature.title}` : ""}` : ""}
          </div>
        </div>
        <div style={{ flex: 2 }}>
          <div style={{ fontSize: 9, color: "#94a3b8", marginBottom: 4 }}>
            Signature
          </div>
          <div
            style={{
              borderBottom: `1px solid ${isSigned ? "#86efac" : "#cbd5e1"}`,
              height: 28,
              fontSize: 14,
              fontStyle: "italic",
              color: "#1e40af",
              lineHeight: "28px",
            }}
          >
            {signature ? signature.name : ""}
          </div>
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 9, color: "#94a3b8", marginBottom: 4 }}>
            Date
          </div>
          <div
            style={{
              borderBottom: `1px solid ${isSigned ? "#86efac" : "#cbd5e1"}`,
              height: 28,
              fontSize: 10,
              color: "#334155",
              lineHeight: "28px",
            }}
          >
            {signature?.date ?? ""}
          </div>
        </div>
      </div>
    </div>
  );
}
